name: MCP Server Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build the project
      run: npm run build

    - name: Run existing tests
      run: npm test

    - name: Start MCP server in background
      run: |
        npm run start:http &
        SERVER_PID=$!
        echo "SERVER_PID=$SERVER_PID" >> $GITHUB_ENV
        # Wait for server to start
        sleep 5
        # Verify server is running
        curl -f http://localhost:3001/sse --max-time 10 || (echo "Server failed to start" && exit 1)

    - name: Test server with FastMCP CLI
      run: |
        echo "Testing MCP server with fastmcp CLI..."
        # Test the server using fastmcp dev command with timeout
        timeout 15s npx fastmcp dev src/index.ts || echo "FastMCP dev test completed (exit code $?)"

    - name: Test server with MCP Inspector
      run: |
        echo "Testing server with MCP Inspector..."
        # Test server with MCP Inspector (will install and test connectivity)
        timeout 10s npx fastmcp inspect src/index.ts || echo "MCP Inspector test completed (exit code $?)"

    - name: Test HTTP server endpoints
      run: |
        echo "Testing HTTP server endpoints..."
        
        # Test that the SSE endpoint is responding with proper headers
        curl -I http://localhost:3001/sse --max-time 5 --silent --fail || echo "SSE endpoint connection test completed"
        
        # Test that the server returns expected SSE format
        timeout 3s curl -N http://localhost:3001/sse --silent | head -n 2 || echo "SSE endpoint response test completed"
        
        echo "HTTP server endpoint tests completed"

    - name: Verify server tools and functionality
      run: |
        echo "Verifying server functionality..."
        
        # Create a simple Node.js test to verify the server exports
        cat > verify_server.js << 'EOF'
        import startServer from "./dist/server/server.js";
        
        async function verifyServer() {
          try {
            console.log("Creating server instance...");
            const server = await startServer();
            
            if (server) {
              console.log("✓ Server instance created successfully");
              console.log("✓ MCP server verification completed");
            } else {
              console.log("✗ Server instance creation failed");
              process.exit(1);
            }
          } catch (error) {
            console.log("✗ Server verification failed:", error.message);
            process.exit(1);
          }
        }
        
        verifyServer();
        EOF
        
        # Run the verification script
        node verify_server.js

    - name: Clean up
      if: always()
      run: |
        if [ ! -z "$SERVER_PID" ]; then
          kill $SERVER_PID || true
        fi